build_and_push:
  image: docker:19.03.12
  services:
  - docker:19.03.12-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker build -t gcr.io/devops-challenge-336815/devops-challenge:0.1 .
    - cat ${GOOGLE_CREDENTIALS} | docker login -u _json_key --password-stdin https://gcr.io/devops-challenge-336815
    - docker push gcr.io/devops-challenge-336815/devops-challenge:0.1
  when: manual
  tags:
    - graas-dind

webserver_tf_apply:
  image: hashicorp/terraform
  script:
    - cd terraform
    - terraform init
    - terraform apply -auto-approve -lock=false
  when: manual
  tags:
    - graas

webserver_tf_destroy:
  image: hashicorp/terraform
  script:
    - cd terraform
    - terraform init
    - terraform destroy -auto-approve -lock=false
  when: manual
  tags:
    - graas